apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::589581698191:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-TW6IPVL1MHWO
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::589581698191:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: | 
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-06-30T04:17:47Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "910"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 834f14d3-da2d-43b5-ab01-aa50f05edb2b
